CC =g++
CFLAGS =-c -Wall
all: hw2_prob1 hw2_prob2 hw2_prob3
hw2_prob1: hw2_prob1.cpp
	$(CC) $(CFLAGS) hw2_prob1.cpp -o hw2_prob1
hw2_prob2: hw2_prob2.cpp
	$(CC) $(CFLAGS) hw2_prob2.cpp -o hw2_prob2
hw2_prob3: hw2_prob3.cpp
	$(CC) $(CFLAGS) hw2_prob3.cpp -o hw2_prob3tar